# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-15 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=30)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
    ]
