# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-18 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosData',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('depatment', models.CharField(max_length=30)),
                ('level', models.CharField(max_length=30)),
                ('uid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('gatewayId', models.CharField(max_length=30)),
            ],
        ),
    ]
