# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-22 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_posdata_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='posdata',
            name='onlineFlag',
            field=models.BooleanField(default=False),
        ),
    ]
